In [16]:
import os
from skimage import io
import cv2
from matplotlib import image as img
from PIL import Image
import numpy as np

In [17]:
pic_file = 'lego.png'
#pic_file = 'indiaflag.jpg'

#dont need to change these
repo_path = os.path.dirname(os.getcwd())
img_path = repo_path + '/img/'
testfile = img_path + pic_file

In [18]:
# lets just read in all of the files in their own unique ways

list_commands = [
    'img_ski = io.imread(testfile)',
    'img_cv0 = cv2.imread(testfile,0)',
    'img_cv1 = cv2.imread(testfile,1)',
    'img_mpl = img.imread(testfile)',
    'img_pil = Image.open(testfile)'
]

for c in list_commands:
    try:
        print('COMMAND: ', c)
        exec(c)
    except Exception as e:
        print(e)
        pass

COMMAND:  img_ski = io.imread(testfile)
COMMAND:  img_cv0 = cv2.imread(testfile,0)
COMMAND:  img_cv1 = cv2.imread(testfile,1)
COMMAND:  img_mpl = img.imread(testfile)
COMMAND:  img_pil = Image.open(testfile)


In [19]:
# FYI: this will check the 3rd argument
# len(img_skimage[0][0])

# now lets print the shapes (aka size)
list_commands = [
    "print('img_ski: ', img_ski.shape)",
    "print('img_cv0: ', img_cv0.shape)",
    "print('img_cv1: ', img_cv1.shape)",
    "print('img_mpl: ', img_mpl.shape)",
    "print('img_pil: ', img_pil.size)"
]

for c in list_commands:
    try:
        #print('COMMAND: ', c)
        exec(c)
    except Exception as e:
        print(e)
        pass

img_ski:  (238, 363, 4)
img_cv0:  (238, 363)
img_cv1:  (238, 363, 3)
img_mpl:  (238, 363, 4)
img_pil:  (363, 238)


In [28]:
# Now lets see if we can reshape them in a way openCV likes it:

list_commands = [
    "img_ski_reshape = np.float32(img_ski.reshape(-1,3))",
    "img_cv0_reshape = np.float32(img_cv0.reshape(-1,3))",
    "img_cv1_reshape = np.float32(img_cv1.reshape(-1,3))",
    "img_mpl_reshape = np.float32(img_mpl.reshape(-1,3))",
    "img_pil_reshape = np.float32(img_pil.reshape(-1,3))"
]

for c in list_commands:
    try:
        print('COMMAND: ', c)
        exec(c)
    except Exception as e:
        print('  > FAIL: ', e)
        pass

print('\n------------------------\n')
list_commands = [
    "print('img_ski: ', img_ski_reshape.shape)",
    "print('img_cv0: ', img_cv0_reshape.shape)",
    "print('img_cv1: ', img_cv1_reshape.shape)",
    "print('img_mpl: ', img_mpl_reshape.shape)",
    "print('img_pil: ', img_pil_reshape.size)"
]

for c in list_commands:
    try:
        #print('COMMAND: ', c)
        exec(c)
    except Exception as e:
        print('  > FAIL: ', e)
        pass

COMMAND:  img_ski_reshape = np.float32(img_ski.reshape(-1,3))
COMMAND:  img_cv0_reshape = np.float32(img_cv0.reshape(-1,3))
COMMAND:  img_cv1_reshape = np.float32(img_cv1.reshape(-1,3))
COMMAND:  img_mpl_reshape = np.float32(img_mpl.reshape(-1,3))
COMMAND:  img_pil_reshape = np.float32(img_pil.reshape(-1,3))
  > FAIL:  'PngImageFile' object has no attribute 'reshape'

------------------------

img_ski:  (115192, 3)
img_cv0:  (28798, 3)
img_cv1:  (86394, 3)
img_mpl:  (115192, 3)
  > FAIL:  name 'img_pil_reshape' is not defined


In [29]:
img_ski

Array([[[179,  25,   0, 255],
        [178,  24,   0, 255],
        [188,  28,   0, 255],
        ...,
        [  0,  74, 179, 255],
        [  0,  75, 179, 255],
        [  0,  74, 179, 255]],

       [[177,  25,   0, 255],
        [177,  23,   0, 255],
        [186,  27,   0, 255],
        ...,
        [  0,  74, 178, 255],
        [  1,  74, 179, 255],
        [  0,  74, 179, 255]],

       [[176,  24,   1, 255],
        [175,  23,   0, 255],
        [184,  27,   0, 255],
        ...,
        [  0,  73, 180, 255],
        [  0,  74, 180, 255],
        [  0,  73, 178, 255]],

       ...,

       [[173,  24,   0, 255],
        [169,  22,   0, 255],
        [166,  22,   1, 255],
        ...,
        [214, 166,   3, 255],
        [215, 167,   3, 255],
        [214, 167,   0, 255]],

       [[171,  22,   0, 255],
        [169,  22,   0, 255],
        [166,  21,   1, 255],
        ...,
        [213, 167,   2, 255],
        [214, 167,   1, 255],
        [215, 168,   0, 255]],

       [[169

In [32]:
img_mpl *= 255

In [33]:
img_mpl

array([[[179.,  25.,   0., 255.],
        [178.,  24.,   0., 255.],
        [188.,  28.,   0., 255.],
        ...,
        [  0.,  74., 179., 255.],
        [  0.,  75., 179., 255.],
        [  0.,  74., 179., 255.]],

       [[177.,  25.,   0., 255.],
        [177.,  23.,   0., 255.],
        [186.,  27.,   0., 255.],
        ...,
        [  0.,  74., 178., 255.],
        [  1.,  74., 179., 255.],
        [  0.,  74., 179., 255.]],

       [[176.,  24.,   1., 255.],
        [175.,  23.,   0., 255.],
        [184.,  27.,   0., 255.],
        ...,
        [  0.,  73., 180., 255.],
        [  0.,  74., 180., 255.],
        [  0.,  73., 178., 255.]],

       ...,

       [[173.,  24.,   0., 255.],
        [169.,  22.,   0., 255.],
        [166.,  22.,   1., 255.],
        ...,
        [214., 166.,   3., 255.],
        [215., 167.,   3., 255.],
        [214., 167.,   0., 255.]],

       [[171.,  22.,   0., 255.],
        [169.,  22.,   0., 255.],
        [166.,  21.,   1., 255.],
        .

In [34]:
img_cv1

array([[[  0,  25, 179],
        [  0,  24, 178],
        [  0,  28, 188],
        ...,
        [179,  74,   0],
        [179,  75,   0],
        [179,  74,   0]],

       [[  0,  25, 177],
        [  0,  23, 177],
        [  0,  27, 186],
        ...,
        [178,  74,   0],
        [179,  74,   1],
        [179,  74,   0]],

       [[  1,  24, 176],
        [  0,  23, 175],
        [  0,  27, 184],
        ...,
        [180,  73,   0],
        [180,  74,   0],
        [178,  73,   0]],

       ...,

       [[  0,  24, 173],
        [  0,  22, 169],
        [  1,  22, 166],
        ...,
        [  3, 166, 214],
        [  3, 167, 215],
        [  0, 167, 214]],

       [[  0,  22, 171],
        [  0,  22, 169],
        [  1,  21, 166],
        ...,
        [  2, 167, 213],
        [  1, 167, 214],
        [  0, 168, 215]],

       [[  0,  22, 169],
        [  0,  22, 167],
        [  0,  22, 165],
        ...,
        [  2, 165, 213],
        [  1, 164, 214],
        [  0, 165, 214]]

In [35]:
img_cv0  #is this greyscale????!??!!

array([[105, 103, 110, ...,  85,  85,  85],
       [103, 103, 109, ...,  85,  85,  85],
       [102, 102, 107, ...,  85,  87,  85],
       ...,
       [101,  98,  96, ..., 174, 175, 174],
       [ 99,  98,  96, ..., 174, 174, 175],
       [ 98,  96,  96, ..., 173, 173, 173]], dtype=uint8)